name: api_gen_e2e_test
description: api_gen E2E Test
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.1 <3.0.0'

#dependencies:
#  path: ^1.7.0

dependencies:
  http: ^0.13.4

dev_dependencies:
  build_runner: ^1.0.0
