name: Go

on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on

    steps:
    - name: Set up Go 1.17
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
      id: go
    
    - uses: actions/checkout@v2

    - uses: actions/cache@v2.1.7
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Run tests
      run: |
        make bootstrap
        make test

  e2e:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on

    steps:
    - name: Set up Go 1.17
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
      id: go
    - uses: nanasess/setup-chromedriver@v1
    - uses: actions/checkout@v2

    - uses: actions/cache@v2.1.7
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-


    - name: Run E2e tests
      run: |
        make bootstrap
        make e2e       
